[package]
name = "day2_2"
version = "0.1.0"
authors = ["Antonio Gutierrez <chibby0ne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
